### ISSUE TITLE
lock_acquire 함수 내에서 조건문 중복 문제

### ISSUE THREAD

**Issue by smi-23** [ChoiWheatley/swjungle-week07-09#16]
https://github.com/ChoiWheatley/swjungle-week07-09/blob/8a58338f4613492abae534abd34c0688299530b9/threads/synch.c#L200-L212

두번째 조건문에서 중복이 발생하므로 if(list_empty(waiters)로 수정해야합니다

**Comment by ChoiWheatley** [comment]
`thread::elem`으로 waiters 안에 들어가는게 맞는데, `lock_acquire` 함수 안에서 선언한 `waiters_max`를 `get_thread_d_elem`으로 하고 있었습니다!!!
