### ISSUE TITLE
test : priority-donate-one에서 block된 쓰레드가 waiters로 들어가지 않는 문제 발생

### ISSUE THREAD

**Issue by smi-23** [ChoiWheatley/swjungle-week07-09#17]
### test = priority-donate-one
test에서 만들어진 thread acquire 1이 락을 얻으려다 block
waiters 에 thread(acquire 1) 를 push-back 후 waiters를 확인하면 해당 thread(acquire 1)를 찾을 수 없고 다른 thread가들어가 있음

<img width="733" alt="image" src="https://github.com/ChoiWheatley/swjungle-week07-09/assets/134453584/7c3b48d5-8139-4616-a846-440b67a33bd5">

**Comment by ChoiWheatley** [comment]
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo chmod 600 /var/swap.1
sudo /sbin/swapon /var/swap.1
