### ISSUE TITLE
proposal(priority scheduling)

### ISSUE THREAD

**Issue by ChoiWheatley** [ChoiWheatley/swjungle-week07-09#4]
# Priority Scheduling 구현 전에 생각한 플로우 

@coding-jjun

## `struct thread` 추가멤버

- `wait_on_lock`: 내가 기다리는 lock.holder
- `donation_list`: 내가 가진 lock**!들!**의 waiter 중 max priority thread
- `d_elem`: `donation_list`의 노드

## method(?)

- `get_priority`: `donation_list`가 비어있지 않으면 `max(donation_list)` else 걍 `thread_current()->priority`
- `set_priority`: 걍 세터

## `lock_acquire`

**`semaphore->value > 0`**

`max(semaphore->waiters)`을 가진 thread의 d_elem을 lock->holder의 donation_list에 push back

**`semaphore->value == 0`**

- lock_acquire에 실패한 thread의 wait_on_lock에 lock->holder의 주소값 추가
	-> lock_holder의 priority가 나보다 낮으면 나의 d_elem을 lock->holder->donation_list에 push back

- [x] ready list에 넣을 때 정렬하면서 넣기 on `thread_unblock`, `thread_yield`
- [x] priority-descending order predicate function

**Comment by ChoiWheatley** [comment]
3. 높은 우선순위 스레드가 락을 해제했을 때 잠시 기부받은 스레드의 우선순위를 원래대로 돌아가게 만들어야함

**Comment by ChoiWheatley** [comment]
4. 하나의 스레드가 두 개 이상의 락을 소유한 경우 여러 스레드로부터 기부받은 내역을 저장해야 함

**Comment by ChoiWheatley** [comment]
## helper functions

- [ ] `get_thread(list_elem) -> thread *`

**Comment by coding-jjun** [comment]
lock_acquire를 성공한 후 그 lock을 획득하기 위해 기다리는 waiters 중 max priority를 가진 thread의 d_elem의 priority가 thread_current의 priority보다 큰 경우에만 donation_list에 push_back하는 조건문을 추가해야한다.
https://github.com/ChoiWheatley/swjungle-week07-09/blob/248a16e25b898f032d00f7f8f5dd50b4110b2133/threads/synch.c#L216-L218

**Comment by ChoiWheatley** [comment]
donation 타이밍이 `lock_acquire` block 이후에 할 것이 아니라 `lock_release`할 때 unblock 될 스레드에게 이루어진다는 점, `soon_unblock` 스레드의 우선순위가 걔의 lock waiters max의 우선순위보다 낮을 때 기부가 이루어진다는 점 이해했습니다. 👍 햎삐 추석~~ 🍁
