### ISSUE TITLE
circular dependencies 문제 

### ISSUE THREAD

**Issue by c4fiber** [ChoiWheatley/swjungle-week07-09#57]
include/vm/vm.h

include/vm/uninit.h

포매터 사용시 include 순서가 바뀌면서 make 실패하는 현상

**Comment by c4fiber** [comment]
uninit.h 와 vm.h의 경우 각각 `ifndef` 구문으로 한번만 정의하도록 제한하고 있지만 내부적으로 include 헤더 위치에 따라서 순환문제가 발생합니다. 이 두 파일에 대해서는 전체 formatting을 수행하지 않아야 합니다.

formatting이 필요한 경우 일부 영역만 포매팅을 적용하는 "Format Selection"을 사용하도록 합니다.

**Comment by ChoiWheatley** [comment]
해당 이슈는 README에 추가하도록 하겠습니다
