### ISSUE TITLE
fix(vm_stack_growth) initializer 추가 제안 + α

### ISSUE THREAD

**Issue by ChoiWheatley** [ChoiWheatley/swjungle-week07-09#58]
현재 `vm_alloc_with_initializer`의 마지막 두 인자가 모두 NULL입니다. `pml4_setter` 함수 포인터를 initializer에 넣어 stack grow 상황에 등록된 새 스택영역에 대한 initializer가 실행될때 알아서 `pml4_set_page`가 되도록 만들어야 할 것입니다.

https://github.com/ChoiWheatley/swjungle-week07-09/blob/7433610c70a45a8b7e5be3a74a01b926da4dd367/vm/vm.c#L164-L169

### 추가

해당 함수는 이미 page fault가 난 상황에서 특정 조건을 만족할 경우 실행되는 것으로 알고있습니다. 그러면 차라리 `vm_stack_growth` 안에서 아예 `get_frame`을 하고 `pml4_set_page`를 하는 건 어떤가요? 위의 방식으로면 스택 크기 증가를 위해서 page fault가 두 번 일어날 것으로 예상됩니다.

**Comment by c4fiber** [comment]
vm_stack_growth -> vm_claim_page -> vm_do_claim_page 순서로 호출하고 있습니다.
vm_do_claim_page에서 vm_get_frame()을 통해 프레임을 받아오므로 미리 frame을 받지 않는게 좋을 것 같습니다.

pml4_set_page()를 수행해야 하는 시점은 fault가 발생해서 vm_do_claim(spt페이지에 frame을 할당한 후 swap_in을 수행 을 수행한 이후가 적절하지 않을까 싶습니다.

swap_in을 호출하게 되면 결국 anon_swap_in이 수행되므로 이 안에서 pml4_set_page()를 사용하는게 어떨까 생각이 듭니다.
