### ISSUE TITLE
question(intr_handler) Round Robin, but yield_on_return false

### ISSUE THREAD

**Issue by ChoiWheatley** [ChoiWheatley/swjungle-week07-09#6]
https://github.com/ChoiWheatley/swjungle-week07-09/blob/f2a8643a34aabcdcf0359543f2d00958a846a0af/threads/interrupt.c#L341-L347

인터럽트 존재 이유가 라운드 로빈 때문인데, 왜 정작 인터럽트 발생후 `thread_yield`를 실행하지 않는가?

**Comment by coding-jjun** [comment]
timer_interrupt가 매 초마다 일어나고 intr_handler가 인터럽트를 처리하기 위해 실행된다.
https://github.com/ChoiWheatley/swjungle-week07-09/blob/f2a8643a34aabcdcf0359543f2d00958a846a0af/threads/interrupt.c#L332-L375
intr_handler는 timer_interrupt가 발생했을 때 실행되어야 할 thread_wakeup( )과 thread_tick( )이 실행된다.
https://github.com/ChoiWheatley/swjungle-week07-09/blob/d2e0971bc271dfc252f7db6946403e2a6aed7812/devices/timer.c#L142-L147
이 때, thread_tick( )에서 4 tick마다 flag인 yield_on_return을 true로 바꿔줘서 intr_handler의 마지막에 `thread_yield`가 발생한다.
https://github.com/ChoiWheatley/swjungle-week07-09/blob/d2e0971bc271dfc252f7db6946403e2a6aed7812/threads/thread.c#L150-L166
